# Generated by Django 4.1.2 on 2022-10-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='status',
            field=models.CharField(choices=[('started', 'Запущен'), ('stopped', 'Остановлен'), ('blocked', 'Заблокирован')], max_length=7, verbose_name='Статус сервера'),
        ),
    ]
